kyma-project/compass-manager

- .reuse/dep5
- LICENSES/Apache-2.0.txt
- README.md
Fixes #20
https://sap.github.io/fosstars-rating-core/oss_rules_of_play_rating.html
> Reuse compliance

- sec-scanners-config.yaml
> Bump image for security scans

- Dockerfile
> Fix security - bump Go image

- sec-scanners-config.yaml
> Bump scans

- config/manager/manager.yaml
- sec-scanners-config.yaml
> Bump sec image, change feature flag to false

- Dockerfile
- go.mod
- go.sum
> Fix security in Compass Manager

- sec-scanners-config.yaml
> Security image bump

- .github/workflows/daily-markdown-link-check.yaml
- .github/workflows/pr-markdown-link-check.yaml
- mlc.config.json
- Add link checker to compass manager
Fixes #26
> Add link checker to compass manager

- controllers/compassmanager_controller.go
> Change App Conn module name

- third_party/machinebox/graphql/README.md
- removes a blog deadlink from 3rd party client
- ...
- ...
> removes a blog deadlink from 3rd party client

- CODE_OF_CONDUCT.md
> Fix link to Code of Conduct

- .github/workflows/golangci-lint.yaml
switches linter go version from 1.21.5 to 1.21
> switches linter go version from 1.21.5 to 1.21

- sec-scanners-config.yaml
> Bump image in security scans

- config/manager/manager.yaml
- main.go
- add URL to Compass Director as env parameter
> Add URL to Compass Director as env parameter

- controllers/compassmanager_controller.go
- Correct metrics for `Ready` status
#28
> Fix metric `"Ready"` bug

- sec-scanners-config.yaml
- bump sec scan image after fixing dependabot PRs
> Bump security image

- config/manager/manager.yaml
- main.go
CMP team are changing URLs, we need to align our components
- change the default (DEV) URL to Compass
- CM will be using the new Compass secret (needs to be created by SRE)
#91
> [Compass Manager] The new URL to Compass System on DEV

- .github/workflows/trivy.yml
> Trigger trivy to fail

- .github/workflows/tests.yml
- controllers/configurator.go
- migrate Compass Manager CI tests from Prow to GitHub Actions
> Create Compass Manager tests in GH Actions

- SECURITY.md
- adds security policy
- ...
- ...
> adds security policy

- .github/workflows/golangci-lint.yaml
- upgrades golangci-lint to v4 in CM
- ...
- ...
> upgrades golangci-lint to v4 in CM

- .github/workflows/golangci-lint.yaml
- .github/workflows/pr-markdown-link-check.yaml
- .github/workflows/run-vuln-check.yaml
- .github/workflows/tests.yml
- .github/workflows/trivy.yml
- controllers/configurator.go
> Rename the GitHub Actions

- sec-scanners-config.yaml
- update the security scan image
> Bump image scans

- .github/workflows/compass-manager.yaml
- fix patterns
- remove manual trivy installation
> Fix pipelines

- .github/workflows/compass-manager.yaml
> Add missing checkout

- .github/workflows/compass-manager.yaml
- update sarif upload action
- install trivy
> Fix trivy workflow

- .github/workflows/compass-manager.yaml
> Remove extra bracket in pipelines

- .github/workflows/compass-manager.yaml
> Add more newlines to summary

- go.mod
- go.sum
> Bump dependencies (fixes trivy)

- .github/workflows/daily-markdown-link-check.yaml
- should fix the broken daily markdown links check 
- ...
- ...
> switches daily-markdown-link-check action to a concrete sha version

- .github/dependabot.yml
- improves dependabot grouping for k8s.io dependencies
- ...
- ...
> improves dependabot grouping for k8s.io dependencies

- internal/util/closer.go
- potential privacy violation in error logging fixed
> fix potential privacy violation in error logging

- .github/workflows/golangci-lint.yaml
- .golangci.yaml
- update golangci-lint workflow
> update golangci-lint workflow

- .github/workflows/compass-manager.yaml
> replace tj-actions/changed-files with step-security/ version

- .github/workflows/golangci-lint.yaml
- Update golangci-lint version to `v1.64.8`
> Fix golangci-lint worlkload

- .github/workflows/compass-manager.yaml
- internal/util/errors.go
- Fix the flaky `unit-test` job in GitHub Actions
> Fix the flaky `unit-test` job in GitHub Actions

- .github/workflows/compass-manager.yaml
> Reorganize structure of the GitHub code coverage action

- .github/workflows/compass-manager.yaml
> Restrict run of the CI to pull_req_target

- .github/workflows/compass-manager.yaml
- sec-scanners-config.yaml
- tag `latest` on top of `main`
- set BDBA to scan `latest`
Released version is scanned by BDBA KCP
> Fix tagging for security scanners

- Dockerfile
Apply recomendation from https://github.com/kyma-project/test-infra/tree/main/cmd/image-builder#cross-compiling-and-caching-for-non-native-architecture-builds
> Update Dockerfile to support multiplatform build

- .github/workflows/golangci-lint.yaml
- Dockerfile
- go.mod
> Bump go 1.25
