kyma-project/compass-manager

.trivy.yaml
- configure trivy security scans
https://github.com/kyma-project/test-infra/pull/7401
=> Configure security scans

.golangci.yaml, Makefile
- add configuration file for `golangci` linter
**Related PR**
[test-infra](https://github.com/kyma-project/test-infra/pull/7445)
=> Configuration for golangci linter

Dockerfile, go.mod
- uses the latest golang-runtime for security reasons
- ...
- ...
=> switches builder to use 1.25.8 golang-runtime in compass-manager

.github/workflows/golangci-lint.yaml, .golangci.yaml
- added Github Action for golangci linter
=> Github Action for Golang linter

config/default/kustomization.yaml, config/default/manager_config_patch.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/leader_election_role.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml
Helm chat update to prevent bugs related with duplication of used pod, and rbac identifiers with other objects on the cluster.
Mainly change `controller-manager` label  to `compass-manager`
Also role and cluster-role changes to be compass-manager specific.
=> Replace default kubebuilder identifiers in helm charts with specific for compass-manager

controllers/compassmanager_controller.go, controllers/compassmanager_controller_test.go
Due to different Kyma CR versions on DEV / STAGE / PROD we need to adjust the way of watching the Application Connector module in CR
- change from watching module in `spec.modules` to `status.modules`
=> Change the way of watching App Conn module

controllers/compassmanager_controller.go, go.mod
For now, the controller is looking for the Application Connector module in `status` field, but we encountered a bug, that PR will fix.
- when `status` on Kyma CR is updated the controller is not triggered unless changes are related to `application-connector` module name
=> Controller triggers only when App Conn module in `status` was updated

config/manager/manager.yaml
Setting feature flag in compass-manager` deployment APP_ENABLED_REGISTRATION to true.
It will enable the function of registration of Kyma runtimes in Compass.
=> Enable runtime registration in compass-manager configuration

controllers/compassmanager_controller.go, controllers/metrics/metrics.go, controllers/status/status.go, controllers/status/status_test.go, go.sum
=> Improve metrics

controllers/compassmanager_controller.go, controllers/dryrun.go, controllers/suite_test.go, go.mod, go.sum, main.go
Implement a dry run switch, which stops Compass Managger from registering runtimes and configuring clusters. Operations that would be made has the dry run flag not been enabled will be logged and tagged `[DRY]`. Compass manager mappings will still be created, with random UUIDS and tagged `compass-manager-dry-run: Yes`
=> Dry run flag

README.md, controllers/compassmanager_controller.go, main.go
- Change dry-run label to `kyma-project.io/cm-dry-run`
- Document env vars
=> Document dry run flag

controllers/compassmanager_controller.go
Dry-run label was added unconditionally. This PR adds the condition
=> Fix dry-run label

controllers/compassmanager_controller.go
- change the invalid Compass label from `global_account_id` to `global_subaccount_id`
=> Change the Compass runtime label

.github/workflows/compass-manager.yaml
=> Fix trivy step order

.github/workflows/compass-manager.yaml
- reformat
- fix checkouts
- add fallbacks
- fix summaries
=> Fix workflow

.github/workflows/compass-manager.yaml
=> Add missing nl

.github/workflows/compass-manager.yaml
- removes trivy as it is failing in most of the times because of an external db connection issue
Example failure
```
2024-11-07T17:03:17Z	ERROR	[vulndb] Failed to download artifact	repo="ghcr.io/aquasecurity/trivy-db:2" err="oci download error: failed to fetch the layer: GET https://ghcr.io/v2/aquasecurity/trivy-db/blobs/sha256:cd1b2cc98f35a3421f3f3040c0a3247edb8f6f91f0b4a211c62fe4abc138811b: TOOMANYREQUESTS: retry-after: 724.762µs, allowed: 44000/minute"
2024-11-07T17:03:17Z	FATAL	Fatal error	init error: DB error: failed to download vulnerability DB: OCI artifact error: failed to download vulnerability DB: failed to download artifact from any source
```
- …
=> Disable trivy

controllers/compassmanager_controller.go, controllers/compassmanager_controller_test.go
Removal of code used to migrate old Runtimes registered by the `Provisioner` service under the management of the `CompassManager` service.
In the removed code, `CompassManager` processed the `compass-runtime-id-for-migration` annotation of the `Kyma` resource produced by KEB and used it to configure the newly created `CompassManagerMapping` resource. The annotation contained the original `RuntimeID` assigned by `Compass` during registration by the Provisioner.
Since the migration process ended a long time ago - this code is no longer required and may cause errors resulting in incorrect registration of the `Kyma Runtime` in `Compass` and potentially affecting users of the `Application-Connector `module.
Translated with DeepL.com (free version)
=> Stop processing of already registered Kyma Runtimes with annotation compass-runtime-id-for-migration

go.mod, go.sum
- replaces golang.org/x/net to v0.33.0
- ...
- ...
=> replaces golang.org/x/net to v0.33.0

config/manager/manager.yaml, controllers/configurator.go, controllers/configurator_test.go, internal/apperrors/apperrors.go, internal/director/directorclient.go, internal/director/directorclient_test.go, main.go
- verify if the runtimeID, that comes from external service Compass is in the correct UUID format
- validate the URL of the token to the Compass Connector to ensure it points to the SAP domain
- perform a sanity check on the Token itself
#54
=> Validation of the 3rd party payload

Makefile, config/crd/bases/operator.kyma-project.io_compassmanagermappings.yaml, internal/apperrors/apperrors.go, internal/apperrors/apperrors_test.go, internal/apperrors/presenter.go, internal/director/directorclient.go, internal/oauth/client.go
In Go 1.24 the `go vet` and printf analyzer are now more strictly checking the format string. More information can be found at [Go 1.24 Release Page](https://tip.golang.org/doc/go1.24#vet).
- aligned with the new approach of printing in Go 1.24,
- updated the controller-gen and k8s version used by the controller test.
=> Change approach of format printing after go 1.24 update
